import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import AdminNav from "./components/AdminNav";
import AdminSideBar from "./components/AdminSideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen =
    cookieStore.get("admin-sidebar-open")?.value === "true" ? true : false;

  return (
    <>
      <SidebarProvider defaultOpen={defaultOpen}>
        <AdminSideBar />
        <main className="w-full h-full p-4 pt-0">
          <AdminNav />
          <div className="py-4">{children}</div>
        </main>
        <ToastContainer />
      </SidebarProvider>
    </>
  );
}
